CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMP DEFAULT now() NOT NULL,
    content TEXT
);

-- note that once you are done making tables and whatnot here, you will need to go
-- to your terminal and create the table, etc
-- for example, in this case, after making the table we go ahead and post this
-- psql -U dunder_mifflin -d knex-practice -f ./blogful-scripts/create.blogful.sql
-- dunder_mifflin being the user, knex-practice being the database, and the rest is
-- pretty much where in the database. 